<?php
return array (
  0 => 
  array (
    'areas_id' => '1',
    'areas_name' => '武汉',
    'areas_description' => '',
    'areas_parentid' => '0',
    'areas_all_parentid' => '',
    'areas_child' => '2',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-11 19:54:57',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  1 => 
  array (
    'areas_id' => '2',
    'areas_name' => '上海',
    'areas_description' => '',
    'areas_parentid' => '0',
    'areas_all_parentid' => '',
    'areas_child' => '2',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-11 22:32:15',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  2 => 
  array (
    'areas_id' => '3',
    'areas_name' => '广州',
    'areas_description' => '',
    'areas_parentid' => '0',
    'areas_all_parentid' => '',
    'areas_child' => '2',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-11 22:33:59',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  3 => 
  array (
    'areas_id' => '4',
    'areas_name' => '北京',
    'areas_description' => '',
    'areas_parentid' => '0',
    'areas_all_parentid' => '',
    'areas_child' => '1',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-11 22:39:01',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  4 => 
  array (
    'areas_id' => '5',
    'areas_name' => '武昌',
    'areas_description' => '',
    'areas_parentid' => '1',
    'areas_all_parentid' => '',
    'areas_child' => '2',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-12 09:21:04',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  5 => 
  array (
    'areas_id' => '8',
    'areas_name' => '浦东',
    'areas_description' => '',
    'areas_parentid' => '2',
    'areas_all_parentid' => '',
    'areas_child' => '1',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-12 09:38:29',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  6 => 
  array (
    'areas_id' => '9',
    'areas_name' => '浦西',
    'areas_description' => '',
    'areas_parentid' => '2',
    'areas_all_parentid' => '',
    'areas_child' => '1',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-12 09:38:52',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  7 => 
  array (
    'areas_id' => '10',
    'areas_name' => '汉口',
    'areas_description' => '',
    'areas_parentid' => '1',
    'areas_all_parentid' => '',
    'areas_child' => '1',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-12 09:39:08',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  8 => 
  array (
    'areas_id' => '11',
    'areas_name' => '洪山',
    'areas_description' => '',
    'areas_parentid' => '1',
    'areas_all_parentid' => '',
    'areas_child' => '1',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-10-12 09:56:22',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
  9 => 
  array (
    'areas_id' => '12',
    'areas_name' => '汉南',
    'areas_description' => '',
    'areas_parentid' => '1',
    'areas_all_parentid' => '',
    'areas_child' => '1',
    'areas_all_children' => '',
    'areas_parentdir' => '',
    'areas_dir' => '',
    'areas_url' => '',
    'areas_image' => '',
    'areas_hits' => '0',
    'areas_status' => '1',
    'areas_sort' => '1',
    'users_id' => '1',
    'areas_addtime' => '2010-12-05 11:27:10',
    'areas_content' => '',
    'areas_remark1' => '',
    'areas_remark2' => '',
    'areas_remark3' => '',
  ),
);
?>