<?php
return array (
  0 => 
  array (
    'cates_id' => '1',
    'modules_id' => '1',
    'cates_name' => '饮食文化',
    'cates_path' => 'yinshi',
    'cates_parentid' => '0',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '1',
    'cate_all_children' => '5,6,7,',
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  1 => 
  array (
    'cates_id' => '2',
    'modules_id' => '1',
    'cates_name' => '消遣娱乐',
    'cates_path' => 'yule',
    'cates_parentid' => '0',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '1',
    'cate_all_children' => '8,9,10,',
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  2 => 
  array (
    'cates_id' => '3',
    'modules_id' => '1',
    'cates_name' => '婚嫁丧娶',
    'cates_path' => 'hunjia',
    'cates_parentid' => '0',
    'cates_all_parentid' => '',
    'cates_parent_dir' => '',
    'cates_all_parent_dir' => '',
    'cates_child' => '1',
    'cate_all_children' => '11,12,13,14,15,',
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  3 => 
  array (
    'cates_id' => '4',
    'modules_id' => '1',
    'cates_name' => '工作生活',
    'cates_path' => 'gongzuo',
    'cates_parentid' => '0',
    'cates_all_parentid' => '',
    'cates_parent_dir' => '',
    'cates_all_parent_dir' => '',
    'cates_child' => '1',
    'cate_all_children' => '16,17,',
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  4 => 
  array (
    'cates_id' => '5',
    'modules_id' => '1',
    'cates_name' => '贵族酒类',
    'cates_path' => 'jiulei',
    'cates_parentid' => '1',
    'cates_all_parentid' => '',
    'cates_parent_dir' => '',
    'cates_all_parent_dir' => '',
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  5 => 
  array (
    'cates_id' => '6',
    'modules_id' => '1',
    'cates_name' => '贵酒',
    'cates_path' => 'guijiu',
    'cates_parentid' => '1',
    'cates_all_parentid' => '',
    'cates_parent_dir' => '',
    'cates_all_parent_dir' => '',
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  6 => 
  array (
    'cates_id' => '7',
    'modules_id' => '1',
    'cates_name' => '名酒',
    'cates_path' => 'mingjiu',
    'cates_parentid' => '1',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  7 => 
  array (
    'cates_id' => '8',
    'modules_id' => '1',
    'cates_name' => '音乐',
    'cates_path' => 'music',
    'cates_parentid' => '2',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  8 => 
  array (
    'cates_id' => '9',
    'modules_id' => '1',
    'cates_name' => '电影',
    'cates_path' => 'movie',
    'cates_parentid' => '2',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  9 => 
  array (
    'cates_id' => '10',
    'modules_id' => '1',
    'cates_name' => '电视剧',
    'cates_path' => 'dianshiju',
    'cates_parentid' => '2',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  10 => 
  array (
    'cates_id' => '11',
    'modules_id' => '1',
    'cates_name' => '约会',
    'cates_path' => 'yuehui',
    'cates_parentid' => '3',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  11 => 
  array (
    'cates_id' => '12',
    'modules_id' => '1',
    'cates_name' => '相亲',
    'cates_path' => 'xiangqin',
    'cates_parentid' => '3',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  12 => 
  array (
    'cates_id' => '13',
    'modules_id' => '1',
    'cates_name' => '结婚',
    'cates_path' => 'jiehun',
    'cates_parentid' => '3',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  13 => 
  array (
    'cates_id' => '14',
    'modules_id' => '1',
    'cates_name' => '离婚',
    'cates_path' => 'lihun',
    'cates_parentid' => '3',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  14 => 
  array (
    'cates_id' => '15',
    'modules_id' => '1',
    'cates_name' => '黄昏恋',
    'cates_path' => 'huanghun',
    'cates_parentid' => '3',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  15 => 
  array (
    'cates_id' => '16',
    'modules_id' => '1',
    'cates_name' => '找工作',
    'cates_path' => 'zhaowork',
    'cates_parentid' => '4',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  16 => 
  array (
    'cates_id' => '17',
    'modules_id' => '1',
    'cates_name' => '招聘',
    'cates_path' => 'zhaopin',
    'cates_parentid' => '4',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  17 => 
  array (
    'cates_id' => '18',
    'modules_id' => '1',
    'cates_name' => '社会动态',
    'cates_path' => 'shehuidongtai',
    'cates_parentid' => '0',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '1',
    'cate_all_children' => '18,',
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
  18 => 
  array (
    'cates_id' => '19',
    'modules_id' => '1',
    'cates_name' => '社会新闻',
    'cates_path' => 'shehuinews',
    'cates_parentid' => '18',
    'cates_all_parentid' => NULL,
    'cates_parent_dir' => NULL,
    'cates_all_parent_dir' => NULL,
    'cates_child' => '0',
    'cate_all_children' => NULL,
    'cates_hits' => '',
    'cate_nav' => '',
    'cates_sort' => '1',
    'cates_status' => '1',
  ),
);
?>