<?php
return array (
  0 => 
  array (
    'channels_id' => '1',
    'channels_name' => '个人系统',
    'channels_path' => 'leehom',
    'channels_url' => '',
    'channels_description' => '趁霓虹灯未亮个人专用管理系统功能',
    'channels_status' => '1',
    'channels_sort' => '1',
    'channels_adduser' => '1',
    'channels_edituser' => '1',
    'channels_addtime' => '2010-12-15 15:36:40',
    'channels_edittime' => '2010-12-15 16:14:52',
    'channels_remark1' => '',
    'channels_remark2' => '',
    'channels_remark3' => '',
  ),
  1 => 
  array (
    'channels_id' => '2',
    'channels_name' => '开发模块',
    'channels_path' => 'empolder',
    'channels_url' => '',
    'channels_description' => '用于收集所有专为开发的模块',
    'channels_status' => '2',
    'channels_sort' => '1',
    'channels_adduser' => '1',
    'channels_edituser' => '1',
    'channels_addtime' => '2010-12-15 18:46:24',
    'channels_edittime' => '2010-12-23 00:34:05',
    'channels_remark1' => '',
    'channels_remark2' => '',
    'channels_remark3' => '',
  ),
  2 => 
  array (
    'channels_id' => '3',
    'channels_name' => '特色功能',
    'channels_path' => 'shtick',
    'channels_url' => '',
    'channels_description' => '用于收集有所特色的功能模块',
    'channels_status' => '1',
    'channels_sort' => '1',
    'channels_adduser' => '1',
    'channels_edituser' => '1',
    'channels_addtime' => '2010-12-15 18:48:20',
    'channels_edittime' => '2010-12-15 18:48:20',
    'channels_remark1' => '',
    'channels_remark2' => '',
    'channels_remark3' => '',
  ),
  3 => 
  array (
    'channels_id' => '4',
    'channels_name' => '功能模块',
    'channels_path' => 'onlyable',
    'channels_url' => '',
    'channels_description' => '单纯的功能，可能没有对应的表，也可能什么表都可以使用',
    'channels_status' => '1',
    'channels_sort' => '1',
    'channels_adduser' => '1',
    'channels_edituser' => '1',
    'channels_addtime' => '2010-12-16 09:31:35',
    'channels_edittime' => '2010-12-16 11:22:39',
    'channels_remark1' => '',
    'channels_remark2' => '',
    'channels_remark3' => '',
  ),
  4 => 
  array (
    'channels_id' => '5',
    'channels_name' => '功能完成',
    'channels_path' => 'Done',
    'channels_url' => '',
    'channels_description' => '用于显示所有功能已经完成的部分。',
    'channels_status' => '1',
    'channels_sort' => '1',
    'channels_adduser' => '1',
    'channels_edituser' => '1',
    'channels_addtime' => '2010-12-17 23:11:33',
    'channels_edittime' => '2010-12-21 23:06:20',
    'channels_remark1' => '',
    'channels_remark2' => '',
    'channels_remark3' => '',
  ),
  5 => 
  array (
    'channels_id' => '6',
    'channels_name' => '完美霓虹',
    'channels_path' => 'LeeToBest',
    'channels_url' => '',
    'channels_description' => '用于显示记录所有代码已经完全满意，完全完成和彻底优化完美的部分。',
    'channels_status' => '1',
    'channels_sort' => '1',
    'channels_adduser' => '1',
    'channels_edituser' => '1',
    'channels_addtime' => '2010-12-21 23:07:43',
    'channels_edittime' => '2010-12-21 23:07:43',
    'channels_remark1' => '',
    'channels_remark2' => '',
    'channels_remark3' => '',
  ),
);
?>