<?php
return array (
  0 => 
  array (
    'modules_id' => '25',
    'modules_name' => '财务日志',
    'modules_path' => 'finacelog',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '用于记录财务',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:41:04',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  1 => 
  array (
    'modules_id' => '26',
    'modules_name' => '邮件服务器',
    'modules_path' => 'mails_server',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '发送邮件的服务器列表数据',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:17:36',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  2 => 
  array (
    'modules_id' => '27',
    'modules_name' => '邮件日志',
    'modules_path' => 'mails_log',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '用户发送邮件和记录邮件发送状态列表',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:37:41',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  3 => 
  array (
    'modules_id' => '28',
    'modules_name' => '问题',
    'modules_path' => 'ask',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '爱问问题列表，所有问题数据',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:37:48',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  4 => 
  array (
    'modules_id' => '29',
    'modules_name' => '回答',
    'modules_path' => 'answers',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '回答问题的数据',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:37:54',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  5 => 
  array (
    'modules_id' => '30',
    'modules_name' => '问题回复',
    'modules_path' => 'ask_posts',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '对问题的回复，爱问系统的一个模块',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:38:00',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  6 => 
  array (
    'modules_id' => '31',
    'modules_name' => '问题统计',
    'modules_path' => 'ask_statistics',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '用于统计问题回答次数，回复次数，点击次数等，可用于问卷，也可用于爱问',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:38:06',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  7 => 
  array (
    'modules_id' => '32',
    'modules_name' => '广告',
    'modules_path' => 'ads',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '广告模块，广告数据内容',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:31:16',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  8 => 
  array (
    'modules_id' => '33',
    'modules_name' => '广告位',
    'modules_path' => 'ads_place',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '广告位，存储，前台页面存放广告的位置和其它详细信息',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:33:41',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  9 => 
  array (
    'modules_id' => '34',
    'modules_name' => '广告统计',
    'modules_path' => 'ads_statistics',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '用于统计广告点击率等',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:34:45',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  10 => 
  array (
    'modules_id' => '35',
    'modules_name' => '地区',
    'modules_path' => 'areas',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '是一个无限级栏目，记录地区的关系数据，很多需要使用地区数据的地方会使用',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:41:16',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  11 => 
  array (
    'modules_id' => '36',
    'modules_name' => '操作日志',
    'modules_path' => 'operalog',
    'modules_cate' => '2',
    'modules_channel' => '1,3,',
    'modules_description' => '操作日志是个人所想，用于时时记录何人何时对何表进行了何种操作。可以方便的查找到所有操作数据库的信息。程序控制前提，没有更新到本表的操作，一律返回去，不再继续执行。',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:40:03',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  12 => 
  array (
    'modules_id' => '37',
    'modules_name' => '评论回复',
    'modules_path' => 'review',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '评论可用作是日志的评论或者其它内容的评论，评论回复就是记录所有回复这些评论的数据。',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:41:29',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  13 => 
  array (
    'modules_id' => '38',
    'modules_name' => '任务提醒',
    'modules_path' => 'testawoke',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '用于记录计划将来的日程和计划，适时提醒的一个模块',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:42:27',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  14 => 
  array (
    'modules_id' => '39',
    'modules_name' => '用户积分',
    'modules_path' => 'users_integrals',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '统计所有注册用户的积分',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:14:39',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  15 => 
  array (
    'modules_id' => '40',
    'modules_name' => '能力项目',
    'modules_path' => 'abletype',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 00:13:51',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  16 => 
  array (
    'modules_id' => '41',
    'modules_name' => '训练项目',
    'modules_path' => 'exercist',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 00:14:02',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  17 => 
  array (
    'modules_id' => '42',
    'modules_name' => 'XML读写',
    'modules_path' => 'xml_re_wr',
    'modules_cate' => '2',
    'modules_channel' => '4,',
    'modules_description' => '用于操作PDF文档的读写操作，同时也可以选择导入导出数据',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:23:46',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  18 => 
  array (
    'modules_id' => '43',
    'modules_name' => '缩略图',
    'modules_path' => 'littlepic',
    'modules_cate' => '2',
    'modules_channel' => '4,',
    'modules_description' => '这里是要演示上传图片，自动生成缩略图的小模块',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:23:39',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  19 => 
  array (
    'modules_id' => '44',
    'modules_name' => '文件资源',
    'modules_path' => 'fileresrcs',
    'modules_cate' => '2',
    'modules_channel' => '4,',
    'modules_description' => '用于文件的上传下载操作，可以进行文件存档操作，以后要考虑文件存档目录搜索的功能',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:23:31',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  20 => 
  array (
    'modules_id' => '45',
    'modules_name' => 'EXL读写',
    'modules_path' => 'exl_re_wr',
    'modules_cate' => '2',
    'modules_channel' => '4,',
    'modules_description' => '用于操作EXCEL文档的读写操作，同时也可以选择导入导出数据，数据直接导入到MYSQL数据库，本人希望尝试一次导入多条数据以提高性能',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:23:24',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  21 => 
  array (
    'modules_id' => '46',
    'modules_name' => 'PDF读写',
    'modules_path' => 'pdf_re_wr',
    'modules_cate' => '2',
    'modules_channel' => '4,',
    'modules_description' => '用于操作PDF文档的读写操作，同时也可以选择导入导出数据',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:23:17',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  22 => 
  array (
    'modules_id' => '47',
    'modules_name' => 'Oracle操作',
    'modules_path' => 'oracle_opera',
    'modules_cate' => '2',
    'modules_channel' => '4,',
    'modules_description' => '用于演示（测试，收藏）Oracle数据库的操作，这是一个PHP联合Oracle的模块',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:23:10',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  23 => 
  array (
    'modules_id' => '48',
    'modules_name' => '活动',
    'modules_path' => 'activitys',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '抽奖，优惠活动，送礼等等各种活动的通用模块',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:34:31',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:43:39',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  24 => 
  array (
    'modules_id' => '49',
    'modules_name' => '活动类别',
    'modules_path' => 'activitys_types',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '各种活动的区别分类',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:35:25',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:43:47',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  25 => 
  array (
    'modules_id' => '50',
    'modules_name' => '活动参与',
    'modules_path' => 'activitys_users',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '活动参与者的统计和记录',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:36:01',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:43:53',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  26 => 
  array (
    'modules_id' => '51',
    'modules_name' => '公告',
    'modules_path' => 'announcement',
    'modules_cate' => '2',
    'modules_channel' => '1,2,',
    'modules_description' => '记录所有展示在前台页面的滚动公告',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:37:03',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 12:21:07',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  27 => 
  array (
    'modules_id' => '52',
    'modules_name' => '积分等级',
    'modules_path' => 'credits',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '设定积分等级信息',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:39:06',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:15:05',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  28 => 
  array (
    'modules_id' => '53',
    'modules_name' => '点击者',
    'modules_path' => 'hits_users',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '记录在线统计中点击里面的点击者相关信息',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:42:01',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:49:14',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  29 => 
  array (
    'modules_id' => '54',
    'modules_name' => '积分项目',
    'modules_path' => 'integrals',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '各种积分的类别栏目',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:43:18',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:15:13',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  30 => 
  array (
    'modules_id' => '55',
    'modules_name' => '关键字',
    'modules_path' => 'keywords',
    'modules_cate' => '2',
    'modules_channel' => '2,1,3,',
    'modules_description' => '用于搜索的关键字管理模块，对应表没有主键',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:44:37',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:15:32',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  31 => 
  array (
    'modules_id' => '56',
    'modules_name' => '语言',
    'modules_path' => 'languages',
    'modules_cate' => '2',
    'modules_channel' => '2,3,',
    'modules_description' => '用于网页切换语言，管理支持语言种类的模块',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:46:19',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:16:08',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  32 => 
  array (
    'modules_id' => '57',
    'modules_name' => '友情链接',
    'modules_path' => 'links',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '友情链接管理模块',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:48:19',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:16:26',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  33 => 
  array (
    'modules_id' => '58',
    'modules_name' => '系统图像',
    'modules_path' => 'person_image',
    'modules_cate' => '2',
    'modules_channel' => '1,2,',
    'modules_description' => '系统个人图像，当用户没有形象照片时，或者不愿意上传照片时，供用户使用的图片资源',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:51:34',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:51:34',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  34 => 
  array (
    'modules_id' => '59',
    'modules_name' => '推荐位',
    'modules_path' => 'positions',
    'modules_cate' => '2',
    'modules_channel' => '2,1,',
    'modules_description' => '推荐位是管理前台醒目位置显示的模块内容，本模块仅管理名称，状态，排序等信息，详细信息，使用详细推荐位表',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 11:58:13',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 11:58:13',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  35 => 
  array (
    'modules_id' => '60',
    'modules_name' => '推荐位详情',
    'modules_path' => 'positions_detail',
    'modules_cate' => '2',
    'modules_channel' => '2,1,',
    'modules_description' => '推荐位的具体的详细的情况',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:00:52',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 00:40:00',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  36 => 
  array (
    'modules_id' => '61',
    'modules_name' => '校园',
    'modules_path' => 'schools',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '搜集存储所有大学以及其它名校的校园情况',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:04:18',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:16:39',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  37 => 
  array (
    'modules_id' => '62',
    'modules_name' => '话题',
    'modules_path' => 'talk',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '探讨话题，统计大众意见，支持，不支持，反对，同意，不同意等等',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:06:17',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:16:49',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  38 => 
  array (
    'modules_id' => '63',
    'modules_name' => '分类',
    'modules_path' => 'types',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '单纯的无限级栏目管理',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:07:18',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 12:07:18',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  39 => 
  array (
    'modules_id' => '64',
    'modules_name' => '话题正反',
    'modules_path' => 'aa_users',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '用于对话题支持反对详情的记录，记录所有参与话题点击的详细信息',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:10:24',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 12:10:24',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  40 => 
  array (
    'modules_id' => '65',
    'modules_name' => '话题评论',
    'modules_path' => 'comments',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '对探讨话题的评论数据收集，评论自身可以被其它用户支持和反对',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:12:26',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 12:12:26',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  41 => 
  array (
    'modules_id' => '66',
    'modules_name' => '收藏',
    'modules_path' => 'favorites',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '统计收藏详情，收藏支持收藏所有对象，本模块对应表没有主键',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:14:04',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 12:14:04',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  42 => 
  array (
    'modules_id' => '67',
    'modules_name' => '收藏者',
    'modules_path' => 'favorites_users',
    'modules_cate' => '2',
    'modules_channel' => '2,',
    'modules_description' => '记录所有收藏者的详情，对应表没有主键',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:15:20',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 12:15:20',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  43 => 
  array (
    'modules_id' => '68',
    'modules_name' => '站内信',
    'modules_path' => 'letters',
    'modules_cate' => '2',
    'modules_channel' => '1,2,',
    'modules_description' => '站内通信，类似小纸条留言等，是不经过外界服务器的简单通信。',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-16 12:17:29',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-16 12:17:29',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  44 => 
  array (
    'modules_id' => '71',
    'modules_name' => 'IP黑名单',
    'modules_path' => 'ips',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 21:44:00',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  45 => 
  array (
    'modules_id' => '101',
    'modules_name' => '系统频道',
    'modules_path' => 'channels',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-17 23:12:18',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  46 => 
  array (
    'modules_id' => '102',
    'modules_name' => '系统设置',
    'modules_path' => 'systems',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 21:19:03',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  47 => 
  array (
    'modules_id' => '103',
    'modules_name' => '模块',
    'modules_path' => 'modules',
    'modules_cate' => '2',
    'modules_channel' => '1,2,3,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-17 23:12:32',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  48 => 
  array (
    'modules_id' => '104',
    'modules_name' => '角色',
    'modules_path' => 'roles',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:21:39',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  49 => 
  array (
    'modules_id' => '105',
    'modules_name' => '管理员',
    'modules_path' => 'admins',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:22:41',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  50 => 
  array (
    'modules_id' => '106',
    'modules_name' => '用户账号',
    'modules_path' => 'users',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:50:57',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  51 => 
  array (
    'modules_id' => '108',
    'modules_name' => '用户信息',
    'modules_path' => 'users_detailed',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:51:07',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  52 => 
  array (
    'modules_id' => '109',
    'modules_name' => '登录日志',
    'modules_path' => 'loginlog',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:51:20',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  53 => 
  array (
    'modules_id' => '111',
    'modules_name' => '用户类别',
    'modules_path' => 'users_type',
    'modules_cate' => '2',
    'modules_channel' => '1,2,5,',
    'modules_description' => '用于设置和管理不同类型的用户',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-20 18:49:55',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:51:29',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  54 => 
  array (
    'modules_id' => '112',
    'modules_name' => '账号申诉',
    'modules_path' => 'accountapeal',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:51:50',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  55 => 
  array (
    'modules_id' => '113',
    'modules_name' => '密保问题',
    'modules_path' => 'problems',
    'modules_cate' => '2',
    'modules_channel' => '1,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-23 11:51:58',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  56 => 
  array (
    'modules_id' => '121',
    'modules_name' => '模型',
    'modules_path' => 'models',
    'modules_cate' => '2',
    'modules_channel' => '1,2,',
    'modules_description' => '用于辨别内容的类别，模型既是六大模型',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-12-20 23:49:55',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-20 23:49:55',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => NULL,
    'modules_remark2' => NULL,
    'modules_remark3' => NULL,
  ),
  57 => 
  array (
    'modules_id' => '122',
    'modules_name' => '栏目',
    'modules_path' => 'cates',
    'modules_cate' => '2',
    'modules_channel' => '1,2,3,5,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-17 23:13:00',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  58 => 
  array (
    'modules_id' => '123',
    'modules_name' => '内容',
    'modules_path' => 'contents',
    'modules_cate' => '1',
    'modules_channel' => '1,2,3,5,',
    'modules_description' => '存储内容',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-17 23:13:08',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  59 => 
  array (
    'modules_id' => '211',
    'modules_name' => '目标类别',
    'modules_path' => 'goalcate',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:22:00',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  60 => 
  array (
    'modules_id' => '212',
    'modules_name' => '目标',
    'modules_path' => 'goal',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:21:41',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  61 => 
  array (
    'modules_id' => '213',
    'modules_name' => '目标分解',
    'modules_path' => 'goalcut',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:22:18',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  62 => 
  array (
    'modules_id' => '214',
    'modules_name' => '动力模块',
    'modules_path' => 'power',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:22:26',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  63 => 
  array (
    'modules_id' => '221',
    'modules_name' => '执行任务',
    'modules_path' => 'taskrun',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:22:32',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  64 => 
  array (
    'modules_id' => '222',
    'modules_name' => '执行日志',
    'modules_path' => 'taskrunlog',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:22:37',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  65 => 
  array (
    'modules_id' => '231',
    'modules_name' => '人脉资源',
    'modules_path' => 'friends',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:22:42',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  66 => 
  array (
    'modules_id' => '232',
    'modules_name' => '人脉高级',
    'modules_path' => 'friendvip',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:22:48',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  67 => 
  array (
    'modules_id' => '233',
    'modules_name' => '客户扩展',
    'modules_path' => 'friendclient',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:23:23',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  68 => 
  array (
    'modules_id' => '234',
    'modules_name' => '人脉联络',
    'modules_path' => 'friendconn',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:24:01',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
  69 => 
  array (
    'modules_id' => '235',
    'modules_name' => '挚友申请',
    'modules_path' => 'friendtobsom',
    'modules_cate' => '2',
    'modules_channel' => '1,',
    'modules_description' => '',
    'modules_addusersid' => '1',
    'modules_addtime' => '2010-11-30 00:40:59',
    'modules_editusersid' => '1',
    'modules_edittime' => '2010-12-15 23:24:17',
    'modules_sort' => '1',
    'modules_status' => '1',
    'modules_remark1' => '',
    'modules_remark2' => '',
    'modules_remark3' => '',
  ),
);
?>